package com.blueberry.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.fullname
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.age
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    public User(Integer id, String fullname, Integer age) {
        this.id = id;
        this.fullname = fullname;
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.id
     *
     * @return the value of t_test.id
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.id
     *
     * @param id the value for t_test.id
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.fullname
     *
     * @return the value of t_test.fullname
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.fullname
     *
     * @param fullname the value for t_test.fullname
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.age
     *
     * @return the value of t_test.age
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.age
     *
     * @param age the value for t_test.age
     *
     * @mbg.generated Thu May 21 22:22:39 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }
    
    private String test = null;
}